-- migrations/0023_socialblade_backfill.sql
-- Social Blade Matrix API daily backfill — yt_subscribers + yt_total_views
-- per day for 4 K-POP groups across [debut-180, debut+90].
-- Generated by scripts/historical_backfill/socialblade_fetch.py.
-- Source: GET /b/youtube/statistics?history=archive
-- yt_total_videos는 daily 응답에 없어 NULL — Wayback (migration 0020) +
-- live collector가 채움.

-- ============================================================
-- PLAVE Social Blade daily (33 rows, 2023-05-09 ~ 2023-06-10)
-- Source: GET /b/youtube/statistics?history=archive
-- ============================================================
INSERT INTO agg_summary
  (group_key, snapshot_at,
   yt_total_videos, yt_total_views, yt_subscribers,
   dc_total_posts, theqoo_posts, instiz_posts,
   naver_total_news, twitter_posts, controversy_count, data_source)
VALUES
  ('plave', '2023-05-09T00:00:00Z', NULL, 18176508, 251000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-10T00:00:00Z', NULL, 18446596, 253000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-11T00:00:00Z', NULL, 18455419, 255000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-12T00:00:00Z', NULL, 18635585, 257000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-13T00:00:00Z', NULL, 18867535, 259000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-14T00:00:00Z', NULL, 19185810, 260000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-15T00:00:00Z', NULL, 19328724, 261000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-16T00:00:00Z', NULL, 19468800, 262000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-17T00:00:00Z', NULL, 19590245, 262000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-18T00:00:00Z', NULL, 19590245, 263000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-19T00:00:00Z', NULL, 19914556, 264000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-20T00:00:00Z', NULL, 20049379, 265000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-21T00:00:00Z', NULL, 20049379, 266000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-22T00:00:00Z', NULL, 20316613, 267000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-23T00:00:00Z', NULL, 20460015, 268000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-24T00:00:00Z', NULL, 20460015, 270000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-25T00:00:00Z', NULL, 21086324, 272000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-26T00:00:00Z', NULL, 21665633, 275000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-27T00:00:00Z', NULL, 22071584, 281000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-28T00:00:00Z', NULL, 22071584, 286000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-29T00:00:00Z', NULL, 22429664, 290000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-30T00:00:00Z', NULL, 22735444, 292000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-05-31T00:00:00Z', NULL, 23041663, 294000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-06-01T00:00:00Z', NULL, 23531894, 296000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-06-02T00:00:00Z', NULL, 23531894, 298000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-06-03T00:00:00Z', NULL, 23781202, 302000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-06-04T00:00:00Z', NULL, 24264433, 306000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-06-05T00:00:00Z', NULL, 24264433, 310000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-06-06T00:00:00Z', NULL, 24941204, 314000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-06-07T00:00:00Z', NULL, 25180177, 317000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-06-08T00:00:00Z', NULL, 25512569, 320000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-06-09T00:00:00Z', NULL, 25512569, 322000, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('plave', '2023-06-10T00:00:00Z', NULL, 25751026, 325000, 0, 0, 0, 0, 0, 0, 'backfill_estimate')
ON CONFLICT(group_key, snapshot_at) DO UPDATE SET
  yt_subscribers = COALESCE(excluded.yt_subscribers, agg_summary.yt_subscribers),
  yt_total_views = COALESCE(excluded.yt_total_views, agg_summary.yt_total_views),
  data_source    = excluded.data_source;

-- SKINZ: API error — 402 Client Error: Payment Required for url: https://matrix.sbapis.com/b/youtube/statistics?query=%40skinzofficial&history=archive

-- MYRAKL: API error — 402 Client Error: Payment Required for url: https://matrix.sbapis.com/b/youtube/statistics?query=%40myrakl_official&history=archive

-- OWIS: API error — 402 Client Error: Payment Required for url: https://matrix.sbapis.com/b/youtube/statistics?query=%40owis_official&history=archive

