-- migrations/0025_naver_api_backfill.sql
-- Naver Open API /v1/search/news.json — weekly article counts.
-- data_source='backfill_exact' since count comes from authoritative
-- API total + bucketed pubDates (no scraping noise).
-- Generated by scripts/historical_backfill/naver_api_fetch.py

-- ============================================================
-- PLAVE Naver API weekly (17 weeks, 2023-04-10 ~ 2025-12-15)
-- Source: Naver Open API /v1/search/news.json sort=date
-- ============================================================
INSERT INTO agg_summary
  (group_key, snapshot_at,
   yt_total_videos, yt_total_views, yt_subscribers,
   dc_total_posts, theqoo_posts, instiz_posts,
   naver_total_news, twitter_posts, controversy_count, data_source)
VALUES
  ('plave', '2023-04-10T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2023-10-09T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2023-10-16T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('plave', '2023-11-20T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2023-11-27T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('plave', '2023-12-11T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('plave', '2024-01-01T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('plave', '2024-02-26T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2024-03-04T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('plave', '2024-04-01T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 10, 0, 0, 'backfill_exact'),
  ('plave', '2024-05-06T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2024-07-22T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2024-12-09T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2025-07-07T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2025-09-01T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2025-10-20T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2025-12-15T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact')
ON CONFLICT(group_key, snapshot_at) DO UPDATE SET
  naver_total_news = excluded.naver_total_news,
  data_source      = CASE
    WHEN agg_summary.data_source = 'live' THEN 'live'
    ELSE excluded.data_source
  END;

-- SKINZ: no articles returned

-- MYRAKL: no articles returned

-- OWIS: no articles returned

-- MIIWAN: no articles returned

-- BDAWN: no articles returned

-- ISEDOL: no articles returned

-- ============================================================
-- STELLIVE Naver API weekly (1 weeks, 2025-04-28 ~ 2025-04-28)
-- Source: Naver Open API /v1/search/news.json sort=date
-- ============================================================
INSERT INTO agg_summary
  (group_key, snapshot_at,
   yt_total_videos, yt_total_views, yt_subscribers,
   dc_total_posts, theqoo_posts, instiz_posts,
   naver_total_news, twitter_posts, controversy_count, data_source)
VALUES
  ('stellive', '2025-04-28T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact')
ON CONFLICT(group_key, snapshot_at) DO UPDATE SET
  naver_total_news = excluded.naver_total_news,
  data_source      = CASE
    WHEN agg_summary.data_source = 'live' THEN 'live'
    ELSE excluded.data_source
  END;

