-- migrations/0030_bigkinds_news_backfill.sql
-- BIGKinds 검색 결과 사용자 다운로드 → weekly news count.
-- data_source='backfill_exact' (authoritative, BIGKinds = 한국 언론사 통합 archive).
-- Generated by scripts/historical_backfill/bigkinds_import.py

-- ============================================================
-- PLAVE BIGKinds weekly (133 weeks, 2022-10-24 ~ 2026-05-04)
-- Source: BIGKinds 검색 결과 사용자 다운로드 → bucketed pubDate
-- ============================================================
INSERT INTO agg_summary
  (group_key, snapshot_at,
   yt_total_videos, yt_total_views, yt_subscribers,
   dc_total_posts, theqoo_posts, instiz_posts,
   naver_total_news, twitter_posts, controversy_count, data_source)
VALUES
  ('plave', '2022-10-24T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2023-02-27T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('plave', '2023-03-13T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('plave', '2023-03-27T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 10, 0, 0, 'backfill_exact'),
  ('plave', '2023-04-10T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2023-07-03T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2023-07-10T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2023-07-24T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2023-07-31T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2023-08-07T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2023-08-14T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2023-08-21T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('plave', '2023-08-28T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 5, 0, 0, 'backfill_exact'),
  ('plave', '2023-09-04T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('plave', '2023-09-11T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('plave', '2023-09-25T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('plave', '2023-10-02T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('plave', '2023-10-09T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2023-10-16T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('plave', '2023-10-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 5, 0, 0, 'backfill_exact'),
  ('plave', '2023-11-13T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('plave', '2023-11-27T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('plave', '2023-12-04T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 7, 0, 0, 'backfill_exact'),
  ('plave', '2023-12-11T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2023-12-18T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2023-12-25T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('plave', '2024-01-01T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('plave', '2024-01-08T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2024-01-15T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('plave', '2024-01-29T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 9, 0, 0, 'backfill_exact'),
  ('plave', '2024-02-12T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2024-02-19T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('plave', '2024-02-26T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 19, 0, 0, 'backfill_exact'),
  ('plave', '2024-03-04T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 12, 0, 0, 'backfill_exact'),
  ('plave', '2024-03-11T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 14, 0, 0, 'backfill_exact'),
  ('plave', '2024-03-18T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 11, 0, 0, 'backfill_exact'),
  ('plave', '2024-03-25T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 10, 0, 0, 'backfill_exact'),
  ('plave', '2024-04-01T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 5, 0, 0, 'backfill_exact'),
  ('plave', '2024-04-08T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2024-04-15T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 8, 0, 0, 'backfill_exact'),
  ('plave', '2024-04-22T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 20, 0, 0, 'backfill_exact'),
  ('plave', '2024-05-06T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('plave', '2024-05-13T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 5, 0, 0, 'backfill_exact'),
  ('plave', '2024-06-10T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('plave', '2024-06-17T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('plave', '2024-07-08T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 8, 0, 0, 'backfill_exact'),
  ('plave', '2024-07-15T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('plave', '2024-07-22T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2024-07-29T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 7, 0, 0, 'backfill_exact'),
  ('plave', '2024-08-05T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('plave', '2024-08-12T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 9, 0, 0, 'backfill_exact'),
  ('plave', '2024-08-19T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 27, 0, 0, 'backfill_exact'),
  ('plave', '2024-08-26T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 8, 0, 0, 'backfill_exact'),
  ('plave', '2024-09-02T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 13, 0, 0, 'backfill_exact'),
  ('plave', '2024-09-09T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 10, 0, 0, 'backfill_exact'),
  ('plave', '2024-09-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2024-09-30T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('plave', '2024-10-07T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 7, 0, 0, 'backfill_exact'),
  ('plave', '2024-10-21T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 13, 0, 0, 'backfill_exact'),
  ('plave', '2024-10-28T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 10, 0, 0, 'backfill_exact'),
  ('plave', '2024-11-04T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 9, 0, 0, 'backfill_exact'),
  ('plave', '2024-11-11T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('plave', '2024-11-18T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 5, 0, 0, 'backfill_exact'),
  ('plave', '2024-11-25T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 9, 0, 0, 'backfill_exact'),
  ('plave', '2024-12-09T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 8, 0, 0, 'backfill_exact'),
  ('plave', '2024-12-16T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('plave', '2024-12-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 5, 0, 0, 'backfill_exact'),
  ('plave', '2025-01-06T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('plave', '2025-01-13T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2025-01-20T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('plave', '2025-01-27T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('plave', '2025-02-03T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 9, 0, 0, 'backfill_exact'),
  ('plave', '2025-02-10T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 7, 0, 0, 'backfill_exact'),
  ('plave', '2025-02-17T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('plave', '2025-02-24T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 8, 0, 0, 'backfill_exact'),
  ('plave', '2025-03-03T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 11, 0, 0, 'backfill_exact'),
  ('plave', '2025-03-10T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('plave', '2025-03-17T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2025-03-24T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 5, 0, 0, 'backfill_exact'),
  ('plave', '2025-03-31T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('plave', '2025-04-07T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('plave', '2025-04-21T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2025-04-28T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2025-05-05T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2025-05-12T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 9, 0, 0, 'backfill_exact'),
  ('plave', '2025-05-19T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2025-05-26T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('plave', '2025-06-02T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2025-06-09T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 7, 0, 0, 'backfill_exact'),
  ('plave', '2025-06-16T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 10, 0, 0, 'backfill_exact'),
  ('plave', '2025-06-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('plave', '2025-06-30T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('plave', '2025-07-07T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 11, 0, 0, 'backfill_exact'),
  ('plave', '2025-07-14T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 7, 0, 0, 'backfill_exact'),
  ('plave', '2025-07-21T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2025-07-28T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 11, 0, 0, 'backfill_exact'),
  ('plave', '2025-08-04T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2025-08-11T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 19, 0, 0, 'backfill_exact'),
  ('plave', '2025-08-18T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 19, 0, 0, 'backfill_exact'),
  ('plave', '2025-08-25T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('plave', '2025-09-01T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 13, 0, 0, 'backfill_exact'),
  ('plave', '2025-09-08T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 11, 0, 0, 'backfill_exact'),
  ('plave', '2025-09-15T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 18, 0, 0, 'backfill_exact'),
  ('plave', '2025-09-22T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 18, 0, 0, 'backfill_exact'),
  ('plave', '2025-09-29T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 5, 0, 0, 'backfill_exact'),
  ('plave', '2025-10-06T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2025-10-13T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 5, 0, 0, 'backfill_exact'),
  ('plave', '2025-10-20T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 5, 0, 0, 'backfill_exact'),
  ('plave', '2025-10-27T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('plave', '2025-11-03T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 10, 0, 0, 'backfill_exact'),
  ('plave', '2025-11-10T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 8, 0, 0, 'backfill_exact'),
  ('plave', '2025-11-17T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 34, 0, 0, 'backfill_exact'),
  ('plave', '2025-11-24T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 26, 0, 0, 'backfill_exact'),
  ('plave', '2025-12-01T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('plave', '2025-12-08T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 5, 0, 0, 'backfill_exact'),
  ('plave', '2025-12-15T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 16, 0, 0, 'backfill_exact'),
  ('plave', '2025-12-22T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('plave', '2025-12-29T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 7, 0, 0, 'backfill_exact'),
  ('plave', '2026-01-05T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 11, 0, 0, 'backfill_exact'),
  ('plave', '2026-01-12T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('plave', '2026-01-19T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('plave', '2026-01-26T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('plave', '2026-02-09T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('plave', '2026-03-02T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('plave', '2026-03-09T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 8, 0, 0, 'backfill_exact'),
  ('plave', '2026-03-16T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('plave', '2026-03-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('plave', '2026-03-30T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('plave', '2026-04-06T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('plave', '2026-04-13T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 7, 0, 0, 'backfill_exact'),
  ('plave', '2026-04-20T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 7, 0, 0, 'backfill_exact'),
  ('plave', '2026-04-27T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 13, 0, 0, 'backfill_exact'),
  ('plave', '2026-05-04T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact')
ON CONFLICT(group_key, snapshot_at) DO UPDATE SET
  naver_total_news = excluded.naver_total_news,
  data_source      = CASE
    WHEN agg_summary.data_source = 'live' THEN 'live'
    ELSE excluded.data_source
  END;

-- ============================================================
-- SKINZ BIGKinds weekly (43 weeks, 2024-01-01 ~ 2026-04-20)
-- Source: BIGKinds 검색 결과 사용자 다운로드 → bucketed pubDate
-- ============================================================
INSERT INTO agg_summary
  (group_key, snapshot_at,
   yt_total_videos, yt_total_views, yt_subscribers,
   dc_total_posts, theqoo_posts, instiz_posts,
   naver_total_news, twitter_posts, controversy_count, data_source)
VALUES
  ('skinz', '2024-01-01T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('skinz', '2024-10-14T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 15, 0, 0, 'backfill_exact'),
  ('skinz', '2024-12-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('skinz', '2025-01-13T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2025-01-27T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2025-02-17T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('skinz', '2025-02-24T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('skinz', '2025-03-10T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('skinz', '2025-03-24T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 7, 0, 0, 'backfill_exact'),
  ('skinz', '2025-03-31T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('skinz', '2025-04-07T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('skinz', '2025-04-14T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('skinz', '2025-04-21T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2025-04-28T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('skinz', '2025-06-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2025-06-30T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2025-07-07T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('skinz', '2025-07-28T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2025-08-11T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2025-08-18T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('skinz', '2025-09-08T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('skinz', '2025-09-15T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('skinz', '2025-09-22T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('skinz', '2025-11-10T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('skinz', '2025-11-17T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2025-11-24T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('skinz', '2025-12-01T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2025-12-08T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('skinz', '2025-12-15T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2025-12-22T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 34, 0, 0, 'backfill_exact'),
  ('skinz', '2025-12-29T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 23, 0, 0, 'backfill_exact'),
  ('skinz', '2026-01-12T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 7, 0, 0, 'backfill_exact'),
  ('skinz', '2026-01-19T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('skinz', '2026-01-26T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2026-02-02T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('skinz', '2026-02-09T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2026-02-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2026-03-02T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 5, 0, 0, 'backfill_exact'),
  ('skinz', '2026-03-09T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 11, 0, 0, 'backfill_exact'),
  ('skinz', '2026-03-16T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2026-03-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2026-04-06T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('skinz', '2026-04-20T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact')
ON CONFLICT(group_key, snapshot_at) DO UPDATE SET
  naver_total_news = excluded.naver_total_news,
  data_source      = CASE
    WHEN agg_summary.data_source = 'live' THEN 'live'
    ELSE excluded.data_source
  END;

-- ============================================================
-- MYRAKL BIGKinds weekly (6 weeks, 2026-01-26 ~ 2026-04-20)
-- Source: BIGKinds 검색 결과 사용자 다운로드 → bucketed pubDate
-- ============================================================
INSERT INTO agg_summary
  (group_key, snapshot_at,
   yt_total_videos, yt_total_views, yt_subscribers,
   dc_total_posts, theqoo_posts, instiz_posts,
   naver_total_news, twitter_posts, controversy_count, data_source)
VALUES
  ('myrakl', '2026-01-26T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('myrakl', '2026-02-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('myrakl', '2026-03-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('myrakl', '2026-03-30T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('myrakl', '2026-04-13T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('myrakl', '2026-04-20T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact')
ON CONFLICT(group_key, snapshot_at) DO UPDATE SET
  naver_total_news = excluded.naver_total_news,
  data_source      = CASE
    WHEN agg_summary.data_source = 'live' THEN 'live'
    ELSE excluded.data_source
  END;

-- ============================================================
-- OWIS BIGKinds weekly (12 weeks, 2025-06-23 ~ 2026-04-20)
-- Source: BIGKinds 검색 결과 사용자 다운로드 → bucketed pubDate
-- ============================================================
INSERT INTO agg_summary
  (group_key, snapshot_at,
   yt_total_videos, yt_total_views, yt_subscribers,
   dc_total_posts, theqoo_posts, instiz_posts,
   naver_total_news, twitter_posts, controversy_count, data_source)
VALUES
  ('owis', '2025-06-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact'),
  ('owis', '2026-01-05T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('owis', '2026-01-12T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 8, 0, 0, 'backfill_exact'),
  ('owis', '2026-01-26T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 5, 0, 0, 'backfill_exact'),
  ('owis', '2026-02-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 16, 0, 0, 'backfill_exact'),
  ('owis', '2026-03-02T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 16, 0, 0, 'backfill_exact'),
  ('owis', '2026-03-09T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 7, 0, 0, 'backfill_exact'),
  ('owis', '2026-03-16T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 12, 0, 0, 'backfill_exact'),
  ('owis', '2026-03-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 32, 0, 0, 'backfill_exact'),
  ('owis', '2026-03-30T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 12, 0, 0, 'backfill_exact'),
  ('owis', '2026-04-06T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 7, 0, 0, 'backfill_exact'),
  ('owis', '2026-04-20T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact')
ON CONFLICT(group_key, snapshot_at) DO UPDATE SET
  naver_total_news = excluded.naver_total_news,
  data_source      = CASE
    WHEN agg_summary.data_source = 'live' THEN 'live'
    ELSE excluded.data_source
  END;

-- MIIWAN: 입력 파일 없음 또는 비어있음 — skip

-- ============================================================
-- BDAWN BIGKinds weekly (62 weeks, 2022-02-21 ~ 2026-05-04)
-- Source: BIGKinds 검색 결과 사용자 다운로드 → bucketed pubDate
-- ============================================================
INSERT INTO agg_summary
  (group_key, snapshot_at,
   yt_total_videos, yt_total_views, yt_subscribers,
   dc_total_posts, theqoo_posts, instiz_posts,
   naver_total_news, twitter_posts, controversy_count, data_source)
VALUES
  ('bdawn', '2022-02-21T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2022-03-28T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 6, 0, 0, 'backfill_exact'),
  ('bdawn', '2022-04-11T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2022-04-25T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2022-05-02T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('bdawn', '2022-05-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2022-06-13T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2022-07-11T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('bdawn', '2022-08-01T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2022-08-22T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('bdawn', '2022-11-07T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('bdawn', '2022-11-28T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-01-02T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-01-16T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-01-23T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-01-30T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 9, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-02-06T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-03-06T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-03-13T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-04-03T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-04-10T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-04-17T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-04-24T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-07-10T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-08-07T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-08-21T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-10-30T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-11-13T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-11-20T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-11-27T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2023-12-18T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2024-02-05T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2024-08-12T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2024-09-09T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2024-09-30T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2024-10-07T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2024-10-21T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2024-11-18T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2025-02-17T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2025-03-10T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2025-03-31T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2025-05-12T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2025-05-19T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2025-05-26T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2025-06-30T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('bdawn', '2025-07-21T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2025-08-04T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2025-09-22T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2025-10-13T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2025-11-03T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2025-11-17T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2026-01-19T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2026-01-26T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('bdawn', '2026-03-02T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('bdawn', '2026-03-09T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('bdawn', '2026-03-16T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 2, 0, 0, 'backfill_exact'),
  ('bdawn', '2026-03-30T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2026-04-06T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2026-04-13T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2026-04-20T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 1, 0, 0, 'backfill_exact'),
  ('bdawn', '2026-04-27T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 4, 0, 0, 'backfill_exact'),
  ('bdawn', '2026-05-04T00:00:00Z', NULL, NULL, NULL, 0, 0, 0, 3, 0, 0, 'backfill_exact')
ON CONFLICT(group_key, snapshot_at) DO UPDATE SET
  naver_total_news = excluded.naver_total_news,
  data_source      = CASE
    WHEN agg_summary.data_source = 'live' THEN 'live'
    ELSE excluded.data_source
  END;

-- ISEDOL: 입력 파일 없음 또는 비어있음 — skip

-- STELLIVE: 입력 파일 없음 또는 비어있음 — skip

