-- migrations/0040_bdawn_socialblade_backfill.sql
-- Social Blade Matrix API daily backfill — yt_subscribers + yt_total_views
-- per day for 4 K-POP groups across [debut-180, debut+90].
-- Generated by scripts/historical_backfill/socialblade_fetch.py.
-- Source: GET /b/youtube/statistics?history=archive
-- yt_total_videos는 daily 응답에 없어 NULL — Wayback (migration 0020) +
-- live collector가 채움.

-- ============================================================
-- BDAWN Social Blade daily (44 rows, 2026-03-24 ~ 2026-05-06)
-- Source: GET /b/youtube/statistics?history=archive
-- ============================================================
INSERT INTO agg_summary
  (group_key, snapshot_at,
   yt_total_videos, yt_total_views, yt_subscribers,
   dc_total_posts, theqoo_posts, instiz_posts,
   naver_total_news, twitter_posts, controversy_count, data_source)
VALUES
  ('bdawn', '2026-03-24T00:00:00Z', NULL, 413910, 1130, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-03-25T00:00:00Z', NULL, 437302, 1150, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-03-26T00:00:00Z', NULL, 443679, 1150, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-03-27T00:00:00Z', NULL, 449739, 1160, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-03-28T00:00:00Z', NULL, 450187, 1160, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-03-29T00:00:00Z', NULL, 450344, 1170, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-03-30T00:00:00Z', NULL, 450447, 1250, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-03-31T00:00:00Z', NULL, 471832, 1410, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-01T00:00:00Z', NULL, 492839, 1750, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-02T00:00:00Z', NULL, 505643, 2160, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-03T00:00:00Z', NULL, 540766, 2660, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-04T00:00:00Z', NULL, 559870, 3270, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-05T00:00:00Z', NULL, 585811, 3290, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-06T00:00:00Z', NULL, 593462, 3290, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-07T00:00:00Z', NULL, 593617, 3290, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-08T00:00:00Z', NULL, 593626, 3290, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-09T00:00:00Z', NULL, 593826, 3290, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-10T00:00:00Z', NULL, 594084, 3310, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-11T00:00:00Z', NULL, 609413, 3320, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-12T00:00:00Z', NULL, 633835, 3350, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-13T00:00:00Z', NULL, 687055, 3390, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-14T00:00:00Z', NULL, 725876, 3450, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-15T00:00:00Z', NULL, 767752, 3480, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-16T00:00:00Z', NULL, 919601, 3500, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-17T00:00:00Z', NULL, 985346, 3520, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-18T00:00:00Z', NULL, 1035686, 3520, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-19T00:00:00Z', NULL, 1071181, 3530, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-20T00:00:00Z', NULL, 1104805, 3550, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-21T00:00:00Z', NULL, 1114179, 3570, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-22T00:00:00Z', NULL, 1122621, 3570, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-23T00:00:00Z', NULL, 1123660, 3590, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-24T00:00:00Z', NULL, 1136068, 3600, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-25T00:00:00Z', NULL, 1151660, 3600, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-26T00:00:00Z', NULL, 1171146, 3610, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-27T00:00:00Z', NULL, 1184291, 3620, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-28T00:00:00Z', NULL, 1221728, 3640, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-29T00:00:00Z', NULL, 1246558, 3660, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-04-30T00:00:00Z', NULL, 1267006, 3800, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-05-01T00:00:00Z', NULL, 1560017, 3920, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-05-02T00:00:00Z', NULL, 1794533, 4010, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-05-03T00:00:00Z', NULL, 1937243, 4100, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-05-04T00:00:00Z', NULL, 2085067, 4190, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-05-05T00:00:00Z', NULL, 2185103, 4330, 0, 0, 0, 0, 0, 0, 'backfill_estimate'),
  ('bdawn', '2026-05-06T00:00:00Z', NULL, 2286740, 4680, 0, 0, 0, 0, 0, 0, 'backfill_estimate')
ON CONFLICT(group_key, snapshot_at) DO UPDATE SET
  yt_subscribers = COALESCE(excluded.yt_subscribers, agg_summary.yt_subscribers),
  yt_total_views = COALESCE(excluded.yt_total_views, agg_summary.yt_total_views),
  data_source    = excluded.data_source;

