#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# dependencies = ["requests>=2.32"]
# ///
"""UR:L 멤버 솔로 채널 SocialBlade daily backfill.

socialblade_fetch.py 의 GROUPS 패턴 (그룹 채널 → agg_summary) 과 달리
멤버 솔로 채널은 youtube_channel_stats 에 INSERT. cli.py 의
_MEMBER_POP_FETCH_SQL 이 `SELECT MAX(cs.subscribers) FROM
youtube_channel_stats cs WHERE cs.channel_id = m.yt_channel_id` 로
매핑하므로 channel_id 단위 daily history 가 들어가면 자동으로 멤버
인기 점수 계산에 활용된다.

V2.33 / 4 credits.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

# socialblade_fetch.py 의 fetch_daily / normalize_daily 재사용
sys.path.insert(0, str(Path(__file__).resolve().parent))
from socialblade_fetch import fetch_daily, normalize_daily  # noqa: E402

CID = os.environ.get("SOCIALBLADE_CLIENT_ID")
TOK = os.environ.get("SOCIALBLADE_TOKEN")
if not CID or not TOK:
    sys.exit("Set SOCIALBLADE_CLIENT_ID + SOCIALBLADE_TOKEN env vars")

MEMBERS = [
    {"name": "모카", "name_en": "Mocha",    "channel_id": "UCiQ3nmup_0jgUOnZ_MQcwKQ"},
    {"name": "랑코", "name_en": "Rangko",   "channel_id": "UCZeHbW3Ifpn4gz9x6OY07JQ"},
    {"name": "마냥", "name_en": "Manyang",  "channel_id": "UCtoHqh381tZlGSmPITK45Lw"},
    {"name": "솜먕", "name_en": "Sommyang", "channel_id": "UCs7qFfGz4UUy4y2GyU8BpAQ"},
]


def to_sql_int(v: int) -> str:
    return "NULL" if v <= 0 else str(v)


def emit_sql_block(name: str, name_en: str, channel_id: str, rows: list[dict]) -> str:
    if not rows:
        return f"-- {name} ({name_en}, {channel_id}): no rows — skip\n"
    values = ",\n  ".join(
        f"('{channel_id}', '{r['date']}T00:00:00Z', "
        f"{to_sql_int(r['subs'])}, {to_sql_int(r['views'])}, NULL)"
        for r in rows
    )
    return f"""-- {name} ({name_en}, {channel_id}): {len(rows)} rows ({rows[0]['date']} ~ {rows[-1]['date']})
INSERT INTO youtube_channel_stats
  (channel_id, snapshot_at, subscribers, total_views, video_count)
VALUES
  {values}
ON CONFLICT(channel_id, snapshot_at) DO UPDATE SET
  subscribers = COALESCE(excluded.subscribers, youtube_channel_stats.subscribers),
  total_views = COALESCE(excluded.total_views, youtube_channel_stats.total_views);
"""


blocks: list[str] = []
summary: list[tuple[str, str, int]] = []
for m in MEMBERS:
    print(f"[{m['name']}] fetching channel_id={m['channel_id']}", file=sys.stderr)
    try:
        data = fetch_daily(m["channel_id"], CID, TOK, history="archive")
    except Exception as e:
        print(f"[{m['name']}] FAIL: {e}", file=sys.stderr)
        summary.append((m["name"], f"FAIL: {e}", 0))
        blocks.append(f"-- {m['name']}: API error — {e}\n")
        continue
    daily = data.get("daily") or []
    rows = normalize_daily(daily, debut_str=None, apply_window=False)
    print(f"  {m['name']}: {len(rows)} rows", file=sys.stderr)
    blocks.append(emit_sql_block(m["name"], m["name_en"], m["channel_id"], rows))
    summary.append((m["name"], "OK", len(rows)))

out = Path(__file__).resolve().parent.parent.parent / "migrations" / "0072_uryael_members_socialblade.sql"
out.write_text(
    "-- migrations/0072_uryael_members_socialblade.sql\n"
    "-- V2.33 — UR:L 멤버 솔로 채널 SocialBlade daily backfill (4 credits).\n"
    "-- Generated by scripts/historical_backfill/uryael_members_sb.py.\n"
    "-- Source: GET /b/youtube/statistics?history=archive\n"
    "-- channel_id 기반 youtube_channel_stats 적재 — cli.py 의\n"
    "-- _MEMBER_POP_FETCH_SQL 가 channel_id 단위 daily 를 활용해\n"
    "-- agg_member_popularity 의 yt_score 를 계산.\n\n"
    + "\n".join(blocks),
    encoding="utf-8",
)
print("\n=== summary ===", file=sys.stderr)
for name, status, n in summary:
    print(f"  {name:<6} {status} ({n} rows)", file=sys.stderr)
print(f"\nMigration written: {out}", file=sys.stderr)
